In [4]:
import pandas as pd
import os

import os

path = './card_data/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.csv')]


benefit_path = './benefit_data/'
benefit_file_list = os.listdir(benefit_path)
benefit_file_list_py = [file for file in benefit_file_list if file.endswith('.csv')]

In [5]:
card = pd.DataFrame()
for i in file_list_py:
    data = pd.read_csv(path + i, header=None, encoding='cp949')
    card = pd.concat([card,data])
    
card = card.reset_index(drop = True)

In [6]:
benefit = pd.DataFrame()
for i in benefit_file_list_py:
    benefit_data = pd.read_csv(benefit_path + i, header=None, encoding='cp949')
    benefit = pd.concat([benefit,benefit_data])
    
benefit = benefit.reset_index(drop = True)

In [7]:
# card.to_csv("card_csv")

,0,1,2,3,4,5,6
0,1.0,신한카드 Hi-Point,신한카드,"해외겸용 8,000원",전월실적없음,VISAmastercardJCB,https://api.card-gorilla.com:8080/storage/card...
1,2.0,신한카드 Love,신한카드,"해외겸용 8,000원",전월실적20만원 이상,VISAmastercardAMEXUnionPay,https://api.card-gorilla.com:8080/storage/card...
2,3.0,신한카드 Lady,신한카드,"해외겸용 5,000원",전월실적30만원 이상,VISAmastercardUnionPay,https://api.card-gorilla.com:8080/storage/card...
3,4.0,SK에너지 신한카드The you,신한카드,"국내전용 7,000원 해외겸용 12,000원",전월실적30만원 이상,VISAmastercardUnionPay,https://api.card-gorilla.com:8080/storage/card...
4,5.0,GS칼텍스 신한카드Dream 100,신한카드,"국내전용 7,000원 해외겸용 12,000원",전월실적30만원 이상,VISA,https://api.card-gorilla.com:8080/storage/card...
...,...,...,...,...,...,...,...
2562,2566.0,Trip to 로카,롯데카드,"국내전용 20,000원 해외겸용 20,000원",전월실적없음,mastercardAMEX,https://api.card-gorilla.com:8080/storage/card...
2563,2567.0,우리동네GS 삼성카드,삼성카드,"국내전용 15,000원 해외겸용 15,000원",전월실적없음,VISA,https://api.card-gorilla.com:8080/storage/card...
2564,2568.0,TMAP & LOGI 행복 체크카드,KB국민카드,국내전용 없음 해외겸용 없음,전월실적없음,mastercard,https://api.card-gorilla.com:8080/storage/card...
2565,2569.0,트래블월렛 우리카드,우리카드,"국내전용 20,000원 해외겸용 20,000원",전월실적없음,VISA,https://api.card-gorilla.com:8080/storage/card...
2566,2572.0,Mile1 하나카드,하나카드,"국내전용 20,000원 해외겸용 20,000원",전월실적없음,UnionPay,https://api.card-gorilla.com:8080/storage/card...

In [8]:
# benefit.to_csv("benefit_data")

,0,1,2,3,4
0,1.0,신한카드 Hi-Point,쇼핑,백화점/할인점/홈쇼핑·온라인몰 1.0~5.0% 적립,롯데/ 현대백화점 마이신한포인트 1.0~5.0% 적립\r\n- 문화센타 등 비쇼핑 ...
1,1.0,신한카드 Hi-Point,모든가맹점,전국 가맹점 0.2~2.0% 적립\r\n해외 가맹점 1~5% 적립,전국 가맹점 0.2~2.0% 적립\r\n- 국내 어디서나 이용한 일시불/할부 금액의...
2,1.0,신한카드 Hi-Point,주유,"S-OIL, 현대오일뱅크 주유 시 리터 당 60원 적립",S-OIL / 현대오일뱅크 주유 시 리터 당 60원 마이신한포인트 적립\r\n- S...
3,1.0,신한카드 Hi-Point,금융,신한투자증권 CMA 결제계좌 0.2% 추가 적립\r\n마이신한포인트 가맹점 추가 적립,신한투자증권 CMA 결제계좌 지정 시 신판이용 금액의 0.2% 마이신한포인트 추가 ...
4,1.0,신한카드 Hi-Point,통신,SK텔레콤/KT/LG U+ 이동통신요금 1.0~5.0% 적립,SK텔레콤/KT/LG U+ 이동통신요금 1.0~5.0% 적립\r\n- SK텔레콤/K...
...,...,...,...,...,...
14820,2569.0,트래블월렛 우리카드,유의사항,꼭 확인하세요!,실적 산정 방법 안내\r\n- 전월실적은 전월 1일부터 말일(매출승인일 기준) 까지...
14821,2572.0,Mile1 하나카드,항공마일리지,UniMile 적립,UniMile 적립 \r\n구분 대상 적립 대상 가맹점 적립율\r\n월 적립한도\r...
14822,2572.0,Mile1 하나카드,공항라운지,[Global 서비스] 인천공항 라운지 무료 입장 및 위탁수화물 서비스,인천공항 라운지 무료 입장 서비스\r\n구분\r\n가맹점 상세\r\n제공횟수\r\n...
14823,2572.0,Mile1 하나카드,프리미엄 서비스,UPI 플래티늄 서비스,UPI 플래티늄 서비스\r\n- 본 상품은 국내외겸용카드로 발급 시 국제브랜드사에서...
14824,2572.0,Mile1 하나카드,유의사항,꼭 확인하세요!,UniMile\r\n- 저비용항공사(LCC:Low Cost Carrier) 6개사(...