In [1]:
import pandas as pd

In [29]:
cardBenefit = pd.read_excel('카드수동.xlsx')

In [30]:
cardBenefit.columns = ['ID', 'NAME', 'BRAND', 'CATEGORY1', 'CATEGORY2', '실적구간',
       '1회당 할인율', '일 할인금액', '일 횟수제한', '일 할인한도', '월 횟수제한', '건당 할인한도',
       '월 할인한도(할인금액기준)', '월 할인한도(결제금액기준)', '비고']

In [35]:
# 빈 행 삭제
print(len(cardBenefit))
cardBenefit.dropna(subset=['ID'], inplace=True)
print(len(cardBenefit))

576
561

In [36]:
# ID 정수로 변경
cardBenefit['ID'] = cardBenefit.loc[:, ['ID']].astype('int')

In [45]:
print(cardBenefit['1회당 할인율'].unique())

[0.1 '리터당 100원' 0.07 0.05 0.5 0.015 '리터당 60원' nan 0.2 0.005]

In [17]:
cardBenefit[cardBenefit['1회당 할인율'].isna()]

,ID,NAME,BRAND,CATEGORY1,CATEGORY2,실적구간,1회당 할인율,일 할인금액,일 횟수제한,일 할인한도,월 횟수제한,건당 할인한도,월 할인한도(할인금액기준),월 할인한도(결제금액기준),비고
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,115.0,굿데이올림카드,KB국민카드,주유소(충전소포함),NaN,2구간(60~120),NaN,NaN,NaN,NaN,NaN,NaN,NaN,400000.0,NaN
116,115.0,굿데이올림카드,KB국민카드,주유소(충전소포함),NaN,3구간(120~),NaN,NaN,NaN,NaN,NaN,NaN,NaN,400000.0,NaN
163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,10.0,신한카드 B.Big(삑),신한카드,영화,CGV,NaN,NaN,4000.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
227,10.0,신한카드 B.Big(삑),신한카드,온라인,인터파크영화,NaN,NaN,1500.0,2.0,NaN,4.0,NaN,NaN,NaN,NaN
230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,NaN,NaN,NaN,NaN,(고른 주유사 1개),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,39.0,신한카드 Deep Oil,신한카드,영화,롯데시네마,1구간(30~70),NaN,5000.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
255,39.0,신한카드 Deep Oil,신한카드,영화,롯데시네마,2구간(70~),NaN,5000.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,45.0,American Express Blue(아멕스블루),삼성카드,교통,버스,1구간(30~60),NaN,NaN,NaN,NaN,NaN,NaN,5000.0,NaN,NaN
349,45.0,American Express Blue(아멕스블루),삼성카드,교통,지하철,1구간(30~60),NaN,NaN,NaN,NaN,NaN,NaN,5000.0,NaN,NaN
350,45.0,American Express Blue(아멕스블루),삼성카드,교통,버스,2구간(60~90),NaN,NaN,NaN,NaN,NaN,NaN,10000.0,NaN,NaN
351,45.0,American Express Blue(아멕스블루),삼성카드,교통,지하철,2구간(60~90),NaN,NaN,NaN,NaN,NaN,NaN,10000.0,NaN,NaN
352,45.0,American Express Blue(아멕스블루),삼성카드,교통,버스,3구간(90~),NaN,NaN,NaN,NaN,NaN,NaN,15000.0,NaN,NaN
353,45.0,American Express Blue(아멕스블루),삼성카드,교통,지하철,3구간(90~),NaN,NaN,NaN,NaN,NaN,NaN,15000.0,NaN,NaN
362,45.0,American Express Blue(아멕스블루),삼성카드,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30000.0,NaN,NaN
369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
416,2354.0,NU Uniq,우리카드,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
444,2354.0,NU Uniq,우리카드,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN